# Generated by Django 4.2.6 on 2023-10-25 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_song"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Song",
            new_name="Soundtrack",
        ),
    ]
