# Generated by Django 4.2.6 on 2023-10-25 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_rename_song_soundtrack"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Soundtrack",
        ),
    ]
